### ISSUE TITLE
ByteBufferCapacityException

### ISSUE THREAD

**Issue by osaure** [mikhail-aksenov/sigrun#19]
Reading a large SEG-Y file causes an exception as a buffer capacity is exceeded:

java.lang.IllegalArgumentException: capacity < 0: (-126144 < 0)
	at java.base/java.nio.Buffer.createCapacityException(Buffer.java:272)
	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:359)
	at com.github.thecoldwine.sigrun.common.SEGYStream.tryReadTrace(SEGYStream.java:95)
	at com.github.thecoldwine.sigrun.common.SEGYStream.access$200(SEGYStream.java:22)

Example file attached
[W2_LN_05_80Hz_34s_500ms_300ms_1ms.zip](https://github.com/thecoldwine/sigrun/files/8247458/W2_LN_05_80Hz_34s_500ms_300ms_1ms.zip).

**Comment by thecoldwine** [comment]
@osaure thanks for the report and many thanks for the data, I will have a look and get back to you.

It is a design flaw it seems, I will think about chunking the data to support large traces.

Question: what version of SEG-Y is it? I didn't do anything with this project for a while, so segy 2 support wasn't added, but I will look at it.

**Comment by osaure** [comment]
Thank quick feedback @thecoldwine.  And this is a neat library so I would really appreciate if the issue is fixed!  Let me know if you need any more information.

**Comment by osaure** [comment]
Sorry for the delay in getting back to you @thecoldwine , I believe it is rev 0 we are using.
